//product
// export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE='PRODUCT_LIST_FAILURE'

// export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAILURE='PRODUCT_DETAIL_FAILURE'

//cart
export const CART_ADD_ITEM='CART_ADD_ITEM'
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM'
